### ISSUE TITLE
Any plans to support Less?

### ISSUE THREAD

**Issue by skirunman** [nathantreid/meteor-css-modules#43] opened 2016-06-15 00:47 UTC
Hi Nathan,
Any plans to support Less so it would be possible to easily using [Essence](http://getessence.io/) with Meteor 1.3.3?
Thanks!
Jim

**Comment by akanix42** [comment] 2016-06-15 13:05
closed as duplicate of #44

**Closed as completed by akanix42** 2016-06-15 13:05 UTC
